{% set name = "album-environments" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: bb32180c8408a726a54a6fa75892a296f97747d001749b14db789890ad95ceaf

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pip
    - python >={{ python_min }}
    - pyyaml >=5.4.1
    - validators >=0.18.2
    - requests >=2.25.1
    - jsonschema >=4.0.0
    - pre-commit >=2.20.0
    - conda-lock >=1.4.0
    - album-solution-api >=0.6.0

test:
  imports:
    - album.environments
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://album.solutions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Album is a framework for unifying computational tools across frameworks, languages, and environments. This package provides the management of virtual environment creation and usage for Album.
  doc_url: https://docs.album.solutions
  dev_url: https://gitlab.com/album-app/album-environments

extra:
  recipe-maintainers:
    - frauzufall
